# hyprsunset -- WRITTEN BY udiksa comfort (Settings > Display > Comfort lighting); edits are overwritten
profile {
    time = 06:09
    identity = true
}

profile {
    time = 18:05
    temperature = 4000
}
